# GitHub Sponsors & Funding

github: [josharsh]
# patreon: user
# open_collective: project
# ko_fi: user
# tidelift: npm/package
# community_bridge: project
# liberapay: user
# issuehunt: user
# custom: ['https://www.buymeacoffee.com/user', 'https://paypal.me/user']
